# syntax=docker/dockerfile:1@sha256:865e5dd094beca432e8c0a1d5e1c465db5f998dca4e439981029b3b81fb39ed5

# renovate: datasource=docker depName=opslabhq/devcontainer/ubuntu-base
ARG VARIANT=jammy@sha256:ffa6f82ebbf33eb1829b59a3719ae688b922792bf8cbe41e94d8400b7e70b392

FROM public.ecr.aws/opslabhq/devcontainer/ubuntu-base:${VARIANT:-latest}

# [Optional] Uncomment this section to install additional OS packages.
# RUN $(which sudo) apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && $(which sudo) apt-get install -y --no-install-recommends <your-package-list-here>
